apiVersion: v1
kind: Service
metadata:
  name: argo-server-nodeport
spec:
  selector:
    app: argo-server
  ports:
    - protocol: TCP
      port: 2746
      targetPort: 2746
      nodePort: 31000  # Optional: Specify a specific port from the NodePort range
  type: NodePort
