kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
#     # You probably don't need this unless you are testing Kubernetes itself.
#     - role: control-plane
#     - role: worker
#     - role: worker


nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000
    hostPort: 31000